name: TFSEC-Dev-Blueprint

on:
  push:
    branches:
      - master
  workflow_dispatch:

# Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
defaults:
  run:
    shell: bash

jobs:

  CI:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup terraform
      uses: hashicorp/setup-terraform@v1

    - name: TFSEC - Check for all
      uses: aquasecurity/tfsec-action@v1.0.0
  